targetNamespace: ''
parameters: {}
packages:
  - name: temperature
    parameters: {}
    annotations: {}
    actions:
      - name: convert
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: {}
        annotations: {}
        limits: {}


