targetNamespace: ''
parameters: {}
packages:
  - name: greetings
    environment:
        FUNC_LVL: ${FUNC_LVL}
    parameters: {}
    annotations: {}
    actions:
      - name: hello
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
environment:
  FUNC_LVL: ${FUNC_LVL}
